# Generated by Django 2.0.2 on 2018-02-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrelationship',
            old_name='follow',
            new_name='user_b',
        ),
        migrations.AlterUniqueTogether(
            name='userrelationship',
            unique_together={('user_a', 'user_b', 'relation_type')},
        ),
    ]
