# Generated by Django 2.0.2 on 2018-02-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180224_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='image_num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
