# Generated by Django 2.0.2 on 2018-04-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180315_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_num',
        ),
    ]
