# Generated by Django 2.0.2 on 2018-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='like_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
