# Generated by Django 2.0.2 on 2018-02-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='like_num',
        ),
    ]
