# Generated by Django 2.0.2 on 2018-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_comment_stauts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_nickname',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
