# Generated by Django 2.0.2 on 2018-04-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20180404_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_nickname',
        ),
    ]
